### ISSUE TITLE
Does not compile with rustc 1.84.1

### ISSUE THREAD

**Issue by felacek** [Pumpkin-MC/Pumpkin#531]
### I've searched existing issues and couldn't find a duplicate.

- [x] I confirm this is not a duplicate.

### Operating System

Arch Linux 6.12.10-arch1-1

### Server Software Version/Commit

Pumpkin 0.1.0-dev (237b335-modified)

### What happened?

Compilation failed with the following error a bunch of times (all from pumpkin-protocol)
```
error[E0277]: `?` couldn't convert the error to `ReadingError`
128.8   --> pumpkin-protocol/src/bytebuf/deserializer.rs:46:49
128.8    |
128.8 46 |         visitor.visit_i8(self.inner.try_get_i8()?)
128.8    |                                                 ^ the trait `From<TryGetError>` is not implemented for `ReadingError`
128.8    |
128.8    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
128.8    = help: the trait `FromResidual<Result<Infallible, E>>` is implemented for `Result<T, F>`
128.8    = note: required for `Result<<V as _::_serde::de::Visitor<'de>>::Value, ReadingError>` to implement `FromResidual<Result<Infallible, TryGetError>>`
```

I fixed it by creating a From trait for ReadingError in `pumpkin-protocol/src/bytebuf/mod.rs`:
```rust
impl From<TryGetError> for ReadingError {
    fn from(error: TryGetError) -> Self {
        if error.requested > error.available {
            return Self::TooLarge("requested too big".to_string());
        } else {
            return Self::Message("idk man".to_string());
        };
    }
}
```
But I have no idea how rust works and if this is the correct solution.

### To Reproduce

run `$ cargo run --release` with rustc version `rustc 1.84.1 (e71f9a9a9 2025-01-27) (Arch Linux rust 1:1.84.1-1)`

### Expected behavior

For the project to compile.

**Comment by Mili-ssm** [comment]
@felacek  could you try to uninstall the rustup tool-chain and then install it again? Also try to do `rustup update stable` to look if you have any error prev to the uninstall thing.

I had an issue with internal cargo files being corrupted when i tried this, the reinstall fixed everything for me, maybe that works for you. (it does not fix the CI/CD issue but for local at least)

**Comment by Snowiiii** [comment]
Did the latest commit fix this issue ?
