### ISSUE TITLE
MIR optimization cycle

### ISSUE THREAD

**Issue by Paladynee** [Pumpkin-MC/Pumpkin#1175]
### I've searched existing issues and couldn't find a duplicate.

- [x] I confirm this is not a duplicate.

### Operating System

Win 10

### Server Software Version/Commit

compiletime error

### What happened?

trying to compile on nightly `rustc 1.92.0-nightly (a454fccb0 2025-09-15)` yields this error:
```
   Compiling pumpkin v0.1.0-dev+1.21.8 (C:\Users\coreign\Desktop\Pumpkin\pumpkin)
error[E0391]: cycle detected when optimizing MIR for `block::registry::<impl at pumpkin\src\block\registry.rs:318:1: 318:19>::update_neighbors::{closure#0}`
    --> pumpkin\src\block\registry.rs:762:7
     |
 762 |       ) {
     |  _______^
 763 | |         for direction in BlockDirection::abstract_block_update_order() {
 764 | |             let pos = position.offset(direction.to_offset());
...    |
 773 | |     }
     | |_____^
     |
note: ...which requires computing layout of `{async fn body of world::<impl at pumpkin\src\world\mod.rs:199:1: 199:11>::replace_with_state_for_neighbor_update()}`...
    --> pumpkin\src\world\mod.rs:2943:17
     |
2943 |                 self.break_block(block_pos, None, flags).await;
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     = note: ...which requires computing layout of `core::mem::maybe_uninit::MaybeUninit<{async fn body of world::<impl at pumpkin\src\world\mod.rs:199:1: 199:11>::break_block()}>`...
     = note: ...which requires computing layout of `core::mem::manually_drop::ManuallyDrop<{async fn body of world::<impl at pumpkin\src\world\mod.rs:199:1: 199:11>::break_block()}>`...
note: ...which requires computing layout of `{async fn body of world::<impl at pumpkin\src\world\mod.rs:199:1: 199:11>::break_block()}`...
    --> pumpkin\src\world\mod.rs:2615:35
     |
2615 |             let broken_state_id = self.set_block_state(position, new_state_id, flags).await;
     |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     = note: ...which requires computing layout of `core::mem::maybe_uninit::MaybeUninit<{async fn body of world::<impl at pumpkin\src\world\mod.rs:199:1: 199:11>::set_block_state()}>`...
     = note: ...which requires computing layout of `core::mem::manually_drop::ManuallyDrop<{async fn body of world::<impl at pumpkin\src\world\mod.rs:199:1: 199:11>::set_block_state()}>`...
note: ...which requires computing layout of `{async fn body of world::<impl at pumpkin\src\world\mod.rs:199:1: 199:11>::set_block_state()}`...
    --> pumpkin\src\world\mod.rs:2529:17
     |
2529 | /                 self.block_registry
2530 | |                     .update_neighbors(
2531 | |                         self,
2532 | |                         position,
...    |
2536 | |                     .await;
     | |__________________________^
     = note: ...which requires computing layout of `core::mem::maybe_uninit::MaybeUninit<{async fn body of block::registry::<impl at pumpkin\src\block\registry.rs:318:1: 318:19>::update_neighbors()}>`...
     = note: ...which requires computing layout of `core::mem::manually_drop::ManuallyDrop<{async fn body of block::registry::<impl at pumpkin\src\block\registry.rs:318:1: 318:19>::update_neighbors()}>`...
     = note: ...which requires computing layout of `{async fn body of block::registry::<impl at pumpkin\src\block\registry.rs:318:1: 318:19>::update_neighbors()}`...
     = note: ...which again requires optimizing MIR for `block::registry::<impl at pumpkin\src\block\registry.rs:318:1: 318:19>::update_neighbors::{closure#0}`, completing the cycle
     = note: cycle used when computing layout of `{async fn body of block::registry::<impl at pumpkin\src\block\registry.rs:318:1: 318:19>::update_neighbors()}`
     = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
```

### To Reproduce

try compile

### Expected behavior

compiles

**Comment by Paladynee** [comment]
at first i thought it happened on nightly rust without any flags but then realized it was a mistake on my part (i forgot to remove `-Zmir-opt-level=3`) and i do realize that `-Zmir-opt-level=3` is not stabilized yet but it is certainly weird to come across a cycle like this.

you can close this issue immediately if you don't plan on investigating this.
